services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes: 
      - wordpress_database:/var/lib/mysql
    networks:
      - inception
    expose: 
      - "3306"
    restart: always
    env_file: .env

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_website_files:/var/www/wordpress
    networks:
      - inception
    expose:
      - "9000"
    restart: always
    env_file: .env

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_database:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
    env_file: .env

volumes:
  wordpress_database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress_website_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  inception: